// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

//go:generate go run github.com/google/wire/cmd/wire
package user

import (
	"github.com/gogf/gf/v2/os/gcfg"
	"github.com/gogf/gf/v2/os/glog"

	"hello_gf/internal/controller"
)

func wireApp() (*gogfApp, func(), error) {
	// 这部分文件是靠wire自动生成的注入，不需要手动维护
	// 建议ghttp.server里面同时包含grpc/http服务
	// 在run的时候就可以同时启动，做优雅重启
	cfg, err := gcfg.New()
	if err != nil {
		return nil, nil, err
	}
	logger := glog.New()
	rpcServer := controller.NewGRPCServer(cfg, logger)
	httpServer := controller.NewHTTPServer(cfg, logger)
	app := newApp(logger, rpcServer, httpServer)
	cleanup := func() {
		// 退出前的操作，可以让用户自定义
		// 需要具体需要让用户自己定义退出时需要执行的方法，然后替换掉这里
	}
	return app, cleanup, nil
}
